### ISSUE TITLE
AddOrUpdate API error

### ISSUE THREAD

**Issue by inluxc** [meilisearch/meilisearch-go#100]
When i update products with the following code;

```
_, err := conn.Client.Documents(Index+sort).AddOrUpdate(jsonParsed.Data()) // => { "updateId": 0 }
if err != nil {
    fmt.Println(err)
    os.Exit(1)
}
```
same times I get the following error? could it be load?

```
unable to execute request (path "PUT /indexes/productPT/documents" with method "Documents.AddOrUpdate"): Put "https://meili.nobrinde.online/indexes/productPT/documents": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
```

**Comment by eskombro** [comment]
Hi @inluxc,

Do you get this error only when trying to use `AddOrUpdate`, but otherwise calls to MeiliSearch engine work? like index creation, or getting documents? Is the request shown in the MeilISearch logs?

**Comment by eskombro** [comment]
@inluxc it is quite hard to understand where the problem is comming from, since your communication with the MeiliSearch instance seems ok and the method is tested.

There has been recent change which introduced a new http client (fasthttp) and I don't know if this introduced some bug. Would you be kind enough to test this?

1. Go to the place where the meilisearch-go library is installed (normally in your GOPATH)
2. do a `git checkout b27b5786f88ce413faa5b5cdb65d3626e56f23c0`
3. Run the program again and see if you get the same error!

Thanks for your help

**Comment by senyast4745** [comment]
@inluxc Hello! This error may be due to the fact that your fasthttp client has a too low read timeout. Try to create your own copy of the fastNTTP client and increase its time...

**Comment by curquiza** [comment]
Hello @inluxc, is this still an issue?

**Comment by inluxc** [comment]
Boo, I will close for now. If I have the error again I will get in touch
