### ISSUE TITLE
Add methods to automatically add/update documents in batches

### ISSUE THREAD

**Issue by curquiza** [meilisearch/meilisearch-go#204]
We need methods to add and update the documents of MeiliSearch in batch instead of letting the users call `addDocuments` in a loop.

- [ ] Add `addDocumentsInBatches`
```
addDocumentsInBatches(documents, batchSize = 1000, primaryKey = nil)
```
`batchSize` and `primaryKey` are optional parameters

- [ ] Add `updateDocumentsInBatches`
```
updateDocumentsInBatches(documents, batchSize = 1000, primaryKey = nil)
```
`batchSize` and `primaryKey` are optional parameters

- [ ] Add tests

Example: https://github.com/meilisearch/meilisearch-python/pull/260

⚠️ This issue is generated, it means `addDocumentsInBatches` andd `updateDocumentsInBatches` might be named differently in this package. Keep the already existing way of naming in this package to stay idiomatic with the language and the repository.
Also, if you are a maintainer, feel free to add any clarification and instruction about this issue related to the specific languages of the repo.

Related to https://github.com/meilisearch/integration-guides/issues/106

Sorry if this is already partially/completely implemented, feel free to let me know about the state of this issue in the repo.

**Comment by krishnaindani** [comment]
@curquiza could I take a look at this?

**Comment by alallema** [comment]
Hi @krishnaindani,
We don't want to assign people to our issues because sometimes people ask to be assigned and never come back, which discourages the real volunteers contributors to open a PR to fix this issue.
We will accept and merge the first PR that fixes correctly and well implements the issue following our [contributing guidelines](https://github.com/meilisearch/meilisearch-js/blob/main/CONTRIBUTING.md).

**Comment by krishnaindani** [comment]
I will start working on it.
