### ISSUE TITLE
Replace all `map[string]interface{}` by the type created for this purpose `Unknow`

### ISSUE THREAD

**Issue by alallema** [meilisearch/meilisearch-go#318]
An "unknown" type is available in the type list but it has not been used or very little in this SDK.
It could be great and cleaner to replace all the `map[string]interface{}` with `Unknow`
```golang
// Unknown is unknown json type
type Unknown map[string]interface{}
```

**Comment by shadowshot-x** [comment]
I can work on this issue

**Comment by alallema** [comment]
Hi @shadowshot-x,
Please, go for it I edit the issue it was a old comment 😃

**Comment by shadowshot-x** [comment]
Awesome. Thank you @alallema

**Comment by a11rew** [comment]
Hi @alallema, should a PR closing this issue change the types of the public APIs too or should changes be limited to internal uses of `map[string]interface{}`?

i.e. should something like [`GetRawIndex`](https://github.com/meilisearch/meilisearch-go/blob/1f355859a3b43151d4cb1496b6b5b8a48530f6bf/client_index.go#L16) return `meilisearch.Unknown` instead of `map[string]interface{}`?

I imagine those might be considered breaking changes?

**Comment by alallema** [comment]
Hi @a11rew,
Thanks for the question, indeed I was just thinking of changing the internal type only to avoid breaking and not forcing people to use our specific type.

**Comment by Ja7ad** [comment]
In v0.28.0 replaced.

https://github.com/meilisearch/meilisearch-go/compare/v0.27.2...v0.28.0
