### ISSUE TITLE
Is there a connection pool?

### ISSUE THREAD

**Issue by kuchaguangjie** [meilisearch/meilisearch-go#364]
Does meilisearch support connection pool (like [this one](https://www.elastic.co/blog/the-go-client-for-elasticsearch-configuration-and-customization)), or even websocket connections ?

If not, do you think it's necessary to add at least one of them?
Thanks.

**Comment by oluademola** [comment]
Hello @kuchaguangjie,

That is a good question, and it is indeed unique. We do not currently support this. However, because this is a feature request, I'd recommend you start a discussion about it on the [product repo](https://github.com/meilisearch/product/discussions/), detailing your use case and any other information that may be useful. This information would be very beneficial to our product team, and I assure you that your suggestion will be evaluated.

Thank you 🙂

**Comment by alallema** [comment]
As the question has been respond I will closed this issue
