### ISSUE TITLE
A Go SDK Refactor?

### ISSUE THREAD

**Issue by eskombro** [meilisearch/meilisearch-go#47]
Every language has it's own specifics, its own rules and good practices. Go is clearly not an exception. But Maintaining several SDKs requires a lot of conciliation between those specific characteristics from one side, and the bigger project (MeiliSearch itself) integrations flow, logic  and structure.

This is why I consider it really important to try to find **as much coherence as possible between the different SDKs ans integrations**. As for now, I feel that the Go SDK is very often considered as the exception, a 'separate case', in every discussion. But this makes maintainability not really cost efficient. Also, as it evolves, it will just keep growing further and further in the future from it's SDK brothers and sisters, and I don't want it to end up alone :)

I spent some time looking to how the other SDKs are built, and why is it that makes it so specific, because I would like to try to make some effort to bring this SDK closer to the other SDKs documentation, logic and structure, to make it easier to evolve, to be used and documented. The work that has been done on it until now is very good (special thanks to @alexisvisco) and I think we can totally keep building over it, and this is why I would like to propose a little refactor for the whole project, keeping as much of this progress as we can, but without fear of exploring new paths.

In my opinion, there is one big thing that can totally give it a new workflow and look, and is not tied to any specificity of Go, but would make it more coherent with the rest of the MeiliSearch project and easier to maintain and live with the other SDKs: the project structure.

- Most MeiliSearch SDKs are using an POO paradigm until now. Go doesn't really exactly implement POO principles, but structures, interfaces and methods tied to them offer us more or less the same functionality, inheritance aside. This is something that is pretty much exploited everywhere in this SDK already. Following that tought, I would like to suggest, first of all, a new Package structure:

  * A Client package, which is responsible for:
    - Index creation, update and retrieval
    - Global MeiliSearch keys handling
    - Server stats, health, sys-info and version

  * An Index package, responsible for:
    - Documents
    - Updates 
    - Search (internal to each index)
    - Index settings
    - Index stats

  * A Custom Error package widely used in the project following previous [error handling discussions](https://github.com/meilisearch/integration-guides/issues/19)

   * Tests, tests everywhere!

I am picturing a repository having one folder at it's root (and all the config files that you normally find in a go repo) called `meilisearch` containing the whole sources of the `meilisearch` package. Inside this folder, something that looks like this (more or less)

![Screenshot 2020-06-16 at 03 07 57](https://user-images.githubusercontent.com/10339833/84720591-bd9acb80-af7e-11ea-930f-ffdf8b45a7d7.png)

This would be a very fast scketch of how a **Possible Getting started** would look like
```go
package main

import (
	"fmt"

	"github.com/eskombro/meilisearch-go/meilisearch/client"
	"github.com/eskombro/meilisearch-go/meilisearch/index"
)

func main() {

	meiliHost := "http://localhost:7700"
	masterKey := "masterKey"
	indexUid := "indexUID"

	// Create an index WITH Master Key
	msClient = client.Create(client.Client{Host: meiliHost, MasterKey: masterKey})
	msIndex = index.Create(msClient, index.IndexConfig{Uid: indexUid})

	documents := []map[string]interface{}{
		{"book_id": 123,  "title": "Pride and Prejudice"},
		{"book_id": 456,  "title": "Le Petit Prince"},
		{"book_id": 1,    "title": "Alice In Wonderland"},
		{"book_id": 1344, "title": "The Hobbit"},
		{"book_id": 4,    "title": "Harry Potter and the Half-Blood Prince"},
		{"book_id": 42,   "title": "The Hitchhiker's Guide to the Galaxy"},
	}
	update := msIndex.addDocuments(documents)
	msIndex.Delete()
}
```

Methods can then be clearly separated, and use the same logic we use in other SDKs. This structure and example of a getting started is for a general idea. It is not only keeping the same logic and structure than the other SDKs, but also closer to what they do at **Algolia** (which I bring into the discussion because it seems to offer a very good experience for the developer):

![Screenshot 2020-06-16 at 03 20 24](https://user-images.githubusercontent.com/10339833/84721395-defcb700-af80-11ea-97b4-d6dc674a52c2.png)

I would really like to have your opinion in this subject, my only goal with this is to **start a general discussion** of where the SDK should be heading to, about what it's **goal should be**, and start having a roadmap for it, that will then transform into issues, and then peoples work and contributions for a great MeiliSearch Go Experience! 🎉 

I would really like to have your opinion on this, @curquiza, @tpayet , @bidoubiwa, @qdequele, @alexisvisco, @derekahn => If you guys have some time to read and give some insigth, I would be very grateful!

**Comment by curquiza** [comment]
I like this suggestion for the new Getting Started. Currently, it's not really convenient to repeat the index uid every time.

Currently:
```go
client.Documents("books").AddOrUpdate(...)
client.Updates("books").Get(...)
client.Search("books").Search(meilisearch.SearchRequest{
    Query: "prince",
    Limit: 10
})
```

With the changes:
```go
msIndex = index.Create(msClient, index.IndexConfig{Uid: "books"})
msIndex.AddDocuments(...)
msIndex.getUpate(...)
msIndex.Search(meilisearch.SearchRequest{
    Query: "prince",
    Limit: 10
})
```

**Comment by alexisvisco** [comment]
The SDK was built with the separation of concerns as a pillar of the go code. It is true that repeating the index in each "client" is a pain, so I agree to change that.

Exposing all the methods in a single object (an index in your reflection example) is terrible from my point of view because there is no separation at all which leads to confusing the user while he's typing and looking for something he needs in his editor.

In your documentation, you are concerned about: index, documents, search, updates, keys, parameters ... When I built the SDK, I saw this and I separated the code with these concepts.

**Like the elasticsearch [go client](https://github.com/olivere/elastic):**
In the elastic go client from olivere (which is far better than the original client from elastic) the client has a list of services on chich you can perform action:
```go
//       Bulk is a namespace
client.Bulk()...
client.Aliases()...
```

**Like the stripe [go clien](https://github.com/stripe/stripe-go)t:**
Exactly the same in the stripe client:

```go
sc := stripeClient.New("sk_test_123", stripe.NewBackends(httpClient))

params := &stripe.CustomerParams{
    Description: stripe.String("Stripe Developer"),
    Email:       stripe.String("gostripe@stripe.com"),
}
//                             Customers is a sub client
customer, err := sc.Customers.New(params)
```

---------

We could mixing up those things to have an Index structure which has a list of sub api.

```go
cm := client.Init(cfg)
index := cm.Index("books")

index.Create(index.IndexConfig{Uid: "books"}) // create the index 

index.Documents.Add(...)
index.Document.Delete(...)

index.Search((meilisearch.SearchRequest{
    Query: "prince",
    Limit: 10
}) // there is only one method for search so there is no need of exposing a subclient

index.Settings.Synonyms.Get(...)
```

IMO: this is far better for the developper experience.

Maybe you should ask this question: are the other SDK a really enjoyable experience as a developer (and not a the developer of the SDK)?

All examples cited above are success SDK stories enjoyed by a lot of developers.

**Comment by curquiza** [comment]
> // there is only one method for search so there is no need of exposing a subclient

The next MeiliSearch version will contain 2 search routes: with GET, and with POST
Cf [this PR](https://github.com/meilisearch/MeiliSearch/pull/735).
I don't know how we are going to handle that in our SDKs, I need to check what Algolia is doing to help us take a decision, be we should keep that in mind 🙂

**Comment by curquiza** [comment]
@alexisvisco 

> Maybe you should ask this question: are the other SDK a really enjoyable experience as a developer (and not as the developer of the SDK)?

As a Ruby developer, I would rather write:
```ruby
index.add_synonyms()
```
than
```ruby
index.settings.synonyms.add()
```

It does not mean the code does not contain any `Settings` class, but the user does not need to manipulate it, from my POV. I know it's subjective, so for me, both solutions are ok in terms of user experience.

I don't really like the user experience of elastic search SDKs, but I like the Stripe one.
But we should keep in mind **the Stripe API is really different from the MeiliSearch one**.
Here are all the reasons why we did not break our SDKs in sub-parts:
- MeiliSearch (the core-engine) manipulates only indexes
- The MeiliSearch API has a few routes, it seemed overkill to break them in more "objects".
- Finally, and that's maybe the more important point, we chose to follow the Algolia clients that are already famous for their user experience and that have been updated by the OS community for a long time. It means the efficacy of their package has already been proven.

Since the user experience between both solutions seems to be subjective, the point is: is it useful in terms of Go code (so for the maintainer) to have multiple files and multiple "classes"? 
**Without forgetting we have not a lot of routes (at the opposite of Stripe API)**

To be honest, I would rather the @eskombro solution because it follows the Algolia client mindset (that looks way more like the MeiliSearch one) but that's just my POV, and I want your opinion @eskombro @alexisvisco 🙂

**Comment by gnur** [comment]
Another thing to consider for a rewrite would be to adapt the way that [asdine/storm](https://github.com/asdine/storm) uses for casting to objects. The exposed methods right now are a bit awkward to use, because in one place to do allow casting (`client.Documents(index).List()`) but in other places (client.Search(index).Search()` there is a `[]interface{}` returned, which actually is a `[]map[string]interface{}`. This seems a bit developer unfriendly.

What storm does is basically force you to always provide a pointer to an object you want to retrieve, like what the `List()` method does.

**Comment by curquiza** [comment]
I'm closing this old issue.
The MeiliSearch team has discussed it, and we want to change the usage of this package to make it more consistent with this other package. The consistency between SDKs is not important but we like rather the other SDK usage than the current one for our users 🙂
@alallema who joined Meili will open issues and PRs related to these new changes.
