### ISSUE TITLE
[v1.10.0] Update documents by function

### ISSUE THREAD

**Issue by brunoocasali** [meilisearch/meilisearch-go#574]
*Following this [central issue](https://github.com/meilisearch/integration-guides/issues/302)*

### Explanation of the feature

Add a new capability to update documents based on a function

Usage: https://meilisearch.notion.site/Update-Documents-by-Function-0cff8fea7655436592e7c8a6de932062

### TODO

- [ ] Add a new method named `updateDocumentsByFunction` calling the newly added `/indexes/:uid/documents/edit`. This method accepts an object as parameter
- [ ] Add tests

⚠️ Please do 1 PR for all of these changes, and not several.

**Comment by Ja7ad** [comment]
@brunoocasali @curquiza Don't have documentation example for transcode?

https://github.com/meilisearch/documentation/blob/main/.code-samples.meilisearch.yaml

**Comment by curquiza** [comment]
Hello @Ja7ad 

this feature is experimental. So, no documentation in a first place.

⚠️ Since it's experimental, I don't recommend you implement it until the community ask for it. It can be work for nothing in the future if we
- break it
- remove it because not used

So, for experimental feature I really recommend not to implement it in repositories like Go SDK, until someone asks for it (of course) because wants to use it!

**Comment by Ja7ad** [comment]
Have issue https://github.com/meilisearch/meilisearch/issues/4956

**Comment by curquiza** [comment]
yes, will be fixed in v1.11 👌
