### ISSUE TITLE
Access _formatted in a search response

### ISSUE THREAD

**Issue by curquiza** [meilisearch/meilisearch-go#6]
Currently, we do not have a way to access the `_formatted` key in a search response if we ask for an `AttributesToHighlight`. 

https://github.com/meilisearch/meilisearch-go/blob/f9427a2cc1e502de018a355ac65e4c81262e703e/types.go#L157-L163

**Comment by alexisvisco** [comment]
After reading the doc it's not totally clear but from what I understood the `_formatted` appear in each  object of the `hits` array right ? 

Since there is no generics in Go I can't wrap the result hits into an object that is containing `_formatted`.

A way to do that is by creating your type and an other with the Formatted key. 

But you pointed out a weakness of the library anyway: the result type is a []interface{} and you can't natively (with the std packages) convert that to a array of your struct. 

A way of quickly doing that is by providing an helper that use https://godoc.org/github.com/mitchellh/mapstructure#Decode. This is the safest and quickest way for getting an array of your custom type from the `hits` response field..

**Comment by curquiza** [comment]
Hi! Thanks for your answer :)

You're completely right, the `_formatted` field is a sub array in `hits`, my bad!

Thanks for providing a temporary solution to get it 🙂

I keep this issue open to think about finding a better way to manage that.

**Comment by eskombro** [comment]
Not offering a definitive solution, but you can always access this kind of elements you don't necessarily defined a structure for by doing a map on your item:

```go
resp, _ = client.Search(indexUID).Search(SearchRequest{
	Query:            "something",
	AttributesToHighlight: []string{"title"},
})
formattedItem := resp.Hits[0].(map[string]interface{})["_formatted"]
```

# output

```
map[book_id:1 tag:Nice book title:<em>Alice</em> In Wonderland]
```

Not beautiful, but works ;)

**Comment by alallema** [comment]
Checked with @curquiza. Closing since a workaround was given. Feel free to re-open if needed
